# Generated by Django 4.0.5 on 2022-12-18 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('tanki', 'Танки'), ('hily', 'Хилы'), ('dd', 'ДД'), ('torgovcy', 'Торговцы'), ('gildmastery', 'Гилдмастеры'), ('kvestgivery', 'Квестгиверы'), ('kuznecy', 'Кузнецы'), ('kozhevniki', 'Кожевники'), ('zelevary', 'Зельевары'), ('zaklinateli', 'Мастера заклинаний')], max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='SomeText...')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='SomeText...')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='unaccepted', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
